spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: harunaydemirinnova@gmail.com
    password: wkye vlkl zfwh vopx
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: email-group
    producer:
      retries: 3
      acks: all