spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: user-management-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/bank-user/**

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/payment-management-realm