spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
           - Path=/auth/**

        - id: user-management-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/bank-user/**
          filters:
            - AuthenticationFilter